### PR TITLE
Add support for unique ID

### PR DESCRIPTION
**Pull request by khronosmoe**
Assigning one entity to area must be done from the UI where unique ID is crucial.
Without unique ID, error reads"This entity ("fan.fan") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail."

### CODE REVIEW

**Comment by syssi** [comment]
Officially a configurable `unique_id` isn't accepted:

https://developers.home-assistant.io/docs/entity_registry_index/

Did you try to remove the `model` from your configuration to have a  `unique_id` generated from some internal details of you Xiaomi device?

**Comment by khronosmoe** [comment]
Only if `model is None`, `unique_id` can be set from `mac_address`. Are there any reasons for this? Can it apply to any model?

**Comment by khronosmoe** [comment]
```python
    devices = []
    miio_device = Device(host, token)
    device_info = await hass.async_add_executor_job(miio_device.info)
    unique_id = f"{model}-{device_info.mac_address}"

    if model is None:
        try:
            model = device_info.model
            _LOGGER.info(
                "%s %s %s detected",
                model,
                device_info.firmware_version,
                device_info.hardware_version,
            )
        except DeviceException as ex:
            raise PlatformNotReady from ex
```

**Comment by syssi** [comment]
The local variable `model` is `None` if you don't set the model at your `configuration.yaml`. In this case the model is auto-detected and a `unique_id` is generated. This applies to all supported models.

The auto-detection and `unique_id` generation is only possible if the device is available at the startup of HA. Some people wanted to be able to setup unavailable / offline devices. In this case the model should be added to the configuration (to avoid the auto-detection) and a `unique_id` cannot be generated anymore.

**Pull request closed without merging**
